import Vue from 'vue';
import { RouteConfig } from 'vue-router';

export enum Kieli {
  fi = 'fi',
  sv = 'sv',
  se = 'se',
  ru = 'ru',
  en = 'en',
}

export interface SovellusVirhe {
  path?: string;
  err?: string;
  state?: object;
  info?: string;
}


export {
  AihekokonaisuudetDto,
  AihekokonaisuusDto,
  DokumenttiDto,
  JarjestysDto,
  KayttajanTietoDto,
  KeskeinenSisaltoalueDto,
  KommenttiDto,
  KoodistoDto,
  KoodistoKoodiDto,
  KoodistoMetadataDto,
  LaajaalainenosaaminenDto,
  LiiteDto,
  LokalisoituTekstiDto,
  Matala,
  OhjeDto,
  OpetuksenKeskeinensisaltoalueDto,
  OpetuksenKohdealueDto,
  OpetuksenTavoiteDto,
  OpetuksenYleisetTavoitteetDto,
  OpetussuunnitelmaBaseDto,
  OpetussuunnitelmaDto,
  OpetussuunnitelmaInfoDto,
  OpetussuunnitelmaJulkinenDto,
  OpetussuunnitelmaKevytDto,
  OpetussuunnitelmaLaajaDto,
  OpetussuunnitelmaLuontiDto,
  OpetussuunnitelmaNimiDto,
  OpetussuunnitelmaStatistiikkaDto,
  OppiaineDto,
  OppiaineLaajaDto,
  OppiaineSuppeaDto,
  OppiaineenVuosiluokkaDto,
  OppiaineenVuosiluokkaKevytDto,
  OppiaineenVuosiluokkakokonaisuusDto,
  OppiaineenVuosiluokkakokonaisuusSuppeaDto,
  OpsOppiaineDto,
  OpsOppiaineKevytDto,
  OpsOppiaineLaajaDto,
  OpsVuosiluokkakokonaisuusDto,
  OpsVuosiluokkakokonaisuusKevytDto,
  OrganisaatioDto,
  OrganisaatioLaajaDto,
  PerusopetuksenPerusteenSisaltoDto,
  PerusteDto,
  PerusteInfoDto,
  PerusteKeskeinensisaltoalueDto,
  PerusteKoulutusDto,
  PerusteLaajaalainenosaaminenDto,
  PerusteOpetuksenkohdealueDto,
  PerusteOpetuksentavoiteDto,
  PerusteOppiaineDto,
  PerusteOppiaineenVuosiluokkakokonaisuusDto,
  PerusteTavoitteenArviointiDto,
  PerusteTekstiKappaleDto,
  PerusteTekstiKappaleViiteDto,
  PerusteTekstiOsaDto,
  PerusteVersionDto,
  PerusteVuosiluokkakokonaisuudenLaajaalainenosaaminenDto,
  PerusteVuosiluokkakokonaisuusDto,
  PoistettuTekstiKappaleDto,
  Puu,
  Reference,
  RevisionDto,
  TavoitteenArviointiDto,
  TekstiKappaleDto,
  TekstiKappaleKevytDto,
  TekstiKappaleViiteKevytDto,
  TekstiosaDto,
  TermiDto,
  Validointi,
  VuosiluokkakokonaisuusDto,
  VuosiluokkakokonaisuusSuppeaDto,
} from '@/generated/api';
