name: Eperusteet-ylops-ui build
on: [workflow_dispatch, push]

jobs:
  build-and-test-eperusteet-ylops-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Print yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          yarn cache dir
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Print npm cache directory
        id: npm-cache-dir
        run: |
          npm config get cache
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build eperusteet-ylops-ui
        run: |
          yarn install --silent
          git submodule update --recursive --init
          cd eperusteet-frontend-utils/vue
          yarn install --silent
          yarn gen:api
          rm -rf node_modules
          cd ../..
          
          yarn lint
          yarn build
          yarn test:unit
