name: Eperusteet-ylops-ui build
#TODO muuta kunhan valmis
on:
  workflow_dispatch:
  push:
    branches:
      - EP-3159-github-actions
    # Workflow ajetaan jos jokin muu kuin markdown tiedosto muuttui
    paths-ignore:
      - '**.md'

jobs:
  build-and-test-eperusteet-ylops-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up Node 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Print yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          yarn cache dir
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Print npm cache directory
        id: npm-cache-dir
        run: |
          npm config get cache
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build eperusteet-ylops-ui
        run: |
          yarn install --silent
          git submodule update --recursive --init
          cd eperusteet-frontend-utils/vue
          yarn install --silent
          yarn gen:api
          rm -rf node_modules
          cd ../..
          
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          
          yarn lint
          yarn build
          yarn test:unit

#          ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
#          ./cc-test-reporter upload-coverage
#          ./cc-test-reporter after-build
