name: Eperusteet-ylops-ui build
on: [workflow_dispatch, push]

jobs:
  build-and-test-eperusteet-ylops-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'  
       
      - name: Enable corepack for nodejs
        run: corepack enable 

      - name: Get backend branch file http status
        id: spec_file_http_status
        run: |
          if [ "$(curl -s -o /dev/null -I -w '%{http_code}' https://raw.githubusercontent.com/Opetushallitus/eperusteet-ylops/${{ github.ref_name }}/generated/ylops.spec.json)" == "200" ] 
          then
            echo spec file found
            echo "EPERUSTEET_YLOPS_SPECFILE=https://raw.githubusercontent.com/Opetushallitus/eperusteet-ylops/${{ github.ref_name }}/generated/ylops.spec.json" >> $GITHUB_ENV
          else
            echo spec file not found
          fi

      - name: Build eperusteet-ylops-ui
        run: |
          git submodule update --recursive --init
          cd eperusteet-frontend-utils/vue
          yarn install --silent
          yarn gen:api
          rm -rf node_modules
          cd ../..
          
          yarn install --silent
          yarn lint
          yarn test
          yarn build
